#!/bin/sh
Description=$1;
if [[ -z "$Description" ]]; then
  Description="Push feito em `date +%Y-%m-%d" "%H:%M:%S` por $USER";
fi
chmod -Rf 0755 .
git add . && git commit -a -m "$Description";
git push -v origin master;
#./clean-assets.sh
